language: python
services:
 - postgresql
python:
 - 3.5
install:
 - pip install psycopg2 coveralls
before_script:
 - psql -c 'create database test;' -U postgres
script:
 - coverage run --source=pydbc setup.py test
after_success:
 - coveralls